In [2]:
import numpy as np

#### Print NumPy array with the element type float in reverse order .

Sample input 
[1 ,-2 ,3 ,4 ,-6 ,2]


Sample output
[2.  -6.   4.   3.   -2.   1.]

In [6]:
a=np.array([1 ,-2 ,3 ,4 ,-6 ,2],dtype='float')
print(a)
print(a[-1::-1])

[ 1. -2.  3.  4. -6.  2.]
[ 2. -6.  4.  3. -2.  1.]


#### Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

output:
[[1,0,0],
[0,1,0],
[0,0,1]]

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [7]:
a=np.diag([1,1,1])
print(a)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Single line of input containing  9 space separated integers.

User provided 1 2 3 4 5 6 7 8 9

Output should be 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [14]:
a=np.array(input("enter 9 numbers:\n").strip('').split(' '))
c=a.reshape(3,3)
print(c)

enter 9 numbers:
1 2 3 4 5 6 7 8 9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


#### Take 3 input from user 
1 the shape
2 row1 values 
3 row2 values 
and create the matrix 


Output should be 


Print the transpose of the given matrix 

Print the created matrix in a 1d array without using shape function 


Sample input :
2 2
1 2
3 4 

Output
[[1 3]
 [2 4]]
[1 2 3 4]

In [11]:
x = int(input("enter the number of rows: "))
y = int(input("enter the number of columns: "))

a=np.zeros((x,y))

print(a)

for i in range(x):
    print("\nEnter Row ",i,"'s Elements...\n")
    for j in range(y):
        a[i][j]=(int(input("Elements: ")))
        
print("Matrix Elements...:\n",a)
z=np.transpose(a)
print("Transpose of Matrix...\n",z)

print("Changing shape of the Matrix....:\n")
n=int(input("enter the required shape( ,j): "))
m=int(input("enter the required shape(i, ): "))
print("Chosen Shape (",n,",",m,")")

c=a.reshape(n,m)
print(c)
# for i in range(n):
#     c[0].append(input("enter values: ")


enter the number of rows: 4
enter the number of columns: 3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Enter Row  0 's Elements...

Elements: 1
Elements: 2
Elements: 3

Enter Row  1 's Elements...

Elements: 4
Elements: 5
Elements: 6

Enter Row  2 's Elements...

Elements: 7
Elements: 8
Elements: 9

Enter Row  3 's Elements...

Elements: 10
Elements: 11
Elements: 12
Matrix Elements...:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Transpose of Matrix...
 [[ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]
 [ 3.  6.  9. 12.]]
Changing shape of the Matrix....:

enter the required shape( ,j): 6
enter the required shape(i, ): 2
Chosen Shape ( 6 , 2 )
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]


#### Write a NumPy program to create a 10x10 matrix, 
in which the elements on the borders will be equal to 1, and inside 0.


sample output
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 
	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 
	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 
	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]

	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]

	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 
	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 
	     [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
	    
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]

	     [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

In [25]:
import numpy as np
a=np.ones((10,10))
b=np.zeros((8,8))
a[1:-1,1:-1] = b
print(a)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### How to find the maximum value in each row of a numpy array 2d? 
a = np.random.randint(1,10, [5,3])

In [29]:
a = np.random.randint(1,10, [5,3])
print(a)
m=0
for i in a:
    m=np.max(i)
    print("Maximim Value in",i,"row is ",m)
            

[[7 2 5]
 [4 1 5]
 [7 7 7]
 [9 3 8]
 [1 2 5]]
Maximim Value in [7 2 5] row is  7
Maximim Value in [4 1 5] row is  5
Maximim Value in [7 7 7] row is  7
Maximim Value in [9 3 8] row is  9
Maximim Value in [1 2 5] row is  5


#### Write a NumPy program to create a 3x4 matrix filled with values ​​from 10 to 21.

sample output
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

In [36]:
a=np.arange(10,22)
c=a.reshape((3,4))
print(c)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#### Write a NumPy program to find common values between two arrays 
Expected Output:
 Array1: [ 0 10 20 40 60]
 Array2: [10, 30, 40]
 Common values between two arrays:
 [10 40]

In [3]:
import numpy as np
array1=[ 0, 10, 20, 40, 60]
array2=[10, 30, 40]
np.intersect1d(array1, array2)

# To intersect more than two arrays, use functools.reduce:

array([10, 40])

#### Write a NumPy program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]



In [41]:
a=np.array([[10,20,30],[20,40,50]])
a.flatten()


array([10, 20, 30, 20, 40, 50])

#### Write a NumPy program to create a new array of 3*5, filled with 2.

Expected Output:
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]

In [45]:
a=np.zeros((3,5))
a.fill(2)
print(a)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


#### Write a NumPy program to compute the multiplication of two given matrixes. 

In [51]:
a=np.array([[2,5,6,3],[6,4,5,2]])
b=np.array([[2,5,6,3],[6,4,5,2]])

print(a)
print(b)
c=np.multiply(a,b)
print(c)


[[2 5 6 3]
 [6 4 5 2]]
[[2 5 6 3]
 [6 4 5 2]]
[[ 4 25 36  9]
 [36 16 25  4]]


#### Write a NumPy program to reverse an array (first element becomes last).

In [53]:
a=np.array([3,4,5,6,7])
print(a[-1::-1])

[7 6 5 4 3]


#### Write a NumPy program to an array converted to a float type.
Sample output:
Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [56]:
a=np.array([1,2,3,4,5], dtype='float')
print(a)

[1. 2. 3. 4. 5.]


#### How to find the duplicate records in a numpy array?

In [58]:
a=np.array([2,3,4,3,5,6,2,4])
c=np.unique(a)
print(c)

[2 3 4 5 6]
