In [1]:
import cmath
a = 1
b = 5
c = 6
# calculate the discriminant
d = (b**2) - (4*a*c)
# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


In [2]:
import numpy as np

a = np.array([[67, 19, 21], [39, 13, 14], [81,24,26]])
d = np.linalg.det(a)

print(d)

-42.99999999999983


In [3]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [4, 4]])
print('array\n',A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print('\n Mean of transponse of A\n',M)
# center columns by subtracting column means
C = A - M
print('\n Centering:\n',C)
# calculate covariance matrix of centered matrix
V = cov(A)
print('\n Covariance..\n',V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print('\n Vectors\n',vectors)
print('\n values\n',values)
# project data
P = vectors.T.dot(C.T)
print('\nProjection\n',P.T)

array
 [[1 2]
 [4 4]]

 Mean of transponse of A
 [2.5 3. ]

 Centering:
 [[-1.5 -1. ]
 [ 1.5  1. ]]

 Covariance..
 [[0.5 0. ]
 [0.  0. ]]

 Vectors
 [[1. 0.]
 [0. 1.]]

 values
 [0.5 0. ]

Projection
 [[-1.5 -1. ]
 [ 1.5  1. ]]


In [4]:
# define a matrix
A = np.array([[1, 2], [4, 4]])
print('array\n',A)

array
 [[1 2]
 [4 4]]


In [5]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print('\n Mean of A\n',M)


 Mean of A
 [2.5 3. ]


In [7]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print('\n\nArray\n',A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print('\n PCA_components\n',pca.components_)
print('\npca.explained_variance\n',pca.explained_variance_)
# transform data
B = pca.transform(A)
print('\n pca.transform\n',B)

values, vectors = eig(V)
print('\n Vectors\n',vectors)
print('\n values\n',values)
# project data
P = vectors.T.dot(C.T)
print('\nProjection\n',P.T)




Array
 [[1 2]
 [3 4]
 [5 6]]

 PCA_components
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

pca.explained_variance
 [8. 0.]

 pca.transform
 [[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]

 Vectors
 [[1. 0.]
 [0. 1.]]

 values
 [0.5 0. ]

Projection
 [[-1.5 -1. ]
 [ 1.5  1. ]]
