# Movie Recommendation with collaborative filtering

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
ratings = pd.read_csv("toy_dataset.csv", index_col=0)
ratings = ratings.fillna(0)
ratings.head(5)

action1  action2  action3  romantic1  romantic2  romantic3
user 1      4.0      5.0      3.0        0.0        2.0        1.0
user 2      5.0      3.0      3.0        2.0        2.0        0.0
user 3      1.0      0.0      0.0        4.0        5.0        4.0
user 4      0.0      2.0      1.0        4.0        0.0        3.0
user 5      1.0      0.0      2.0        3.0        3.0        4.0

In [15]:
def standardize(row):
    new_row = ((row-row.mean()) / row.max() -row.min())
    return new_row

ratings_std = ratings.apply(standardize)
print(ratings_std)
print("\n")
print("-"*40)

# we are transposing, since we want similarity between items which need to be in same row
item_similarity = cosine_similarity(ratings_std.T)
print("Numpy array based on which we recommend")
print(item_similarity)

        action1  action2   action3  romantic1  romantic2  romantic3
user 1     0.36      0.6  0.400000      -0.65      -0.08      -0.35
user 2     0.56      0.2  0.400000      -0.15      -0.08      -0.60
user 3    -0.24     -0.4 -0.600000       0.35       0.52       0.40
user 4    -0.44      0.0 -0.266667       0.35      -0.48       0.15
user 5    -0.24     -0.4  0.066667       0.10       0.12       0.40


----------------------------------------
Numpy array based on which we recommend
[[ 1.          0.70668875  0.81368151 -0.79941088 -0.02539184 -0.91410609]
 [ 0.70668875  1.          0.72310153 -0.84515425 -0.5189993  -0.84337386]
 [ 0.81368151  0.72310153  1.         -0.84794611 -0.3799803  -0.80218063]
 [-0.79941088 -0.84515425 -0.84794611  1.          0.14803913  0.72374686]
 [-0.02539184 -0.5189993  -0.3799803   0.14803913  1.          0.39393939]
 [-0.91410609 -0.84337386 -0.80218063  0.72374686  0.39393939  1.        ]]


In [18]:
#create datafram of similarity
item_similarity_df = pd.DataFrame(item_similarity, index = ratings.columns, columns=ratings.columns)
item_similarity_df

action1   action2   action3  romantic1  romantic2  romantic3
action1    1.000000  0.706689  0.813682  -0.799411  -0.025392  -0.914106
action2    0.706689  1.000000  0.723102  -0.845154  -0.518999  -0.843374
action3    0.813682  0.723102  1.000000  -0.847946  -0.379980  -0.802181
romantic1 -0.799411 -0.845154 -0.847946   1.000000   0.148039   0.723747
romantic2 -0.025392 -0.518999 -0.379980   0.148039   1.000000   0.393939
romantic3 -0.914106 -0.843374 -0.802181   0.723747   0.393939   1.000000